### ISSUE TITLE
effects dont show up lol

### ISSUE THREAD

**Issue by odiplol** [byxor/thug-pro-reshade#3] opened 2023-08-01 15:48 UTC
![image](https://github.com/byxor/thug-pro-reshade/assets/129446279/7f71a18f-9046-420b-910b-54d2e6ec01dd)
tried reinstalling multiple times

**Comment by byxor** [comment] 2023-08-01 18:34
Good find. Closing this as a duplicate of #2, but thanks for sharing; it's helpful to know multiple people are seeing the same issue

**Closed as not planned by byxor** 2023-08-01 18:34 UTC

**Comment by odiplol** [comment] 2023-08-01 20:09
cool, should of just commented under that post lol.
